---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        image: $E2E_IMAGE
        args:
        - -v
        - --enable-leader-election=false
