resources:
- ../../../config/manager
- ../../../config/rbac
- ../../../config/namespace
patchesStrategicMerge:
- deployment.yaml
namespace: espejo-system
namePrefix: espejo-

commonLabels:
  app.kubernetes.io/name: e2e
  app.kubernetes.io/managed-by: kustomize
