# permissions for end users to view syncconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncconfig-viewer-role
rules:
- apiGroups:
  - sync.appuio.ch
  resources:
  - syncconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.appuio.ch
  resources:
  - syncconfigs/status
  verbs:
  - get
