apiVersion: sync.appuio.ch/v1alpha1
kind: SyncConfig
metadata:
  name: syncconfig-sample
spec:
  namespaceSelector:
    matchNames:
    - default
  syncItems:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: espejo-test-data
    data:
      NAMESPACE: ${PROJECT_NAME}
