name: E2E

on:
  pull_request:
    branches:
    - master

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2 | cut -d "." -f 1,2)" >> $GITHUB_ENV
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run e2e tests
      run: make crd e2e-test -e bats_args="--report-formatter junit"
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/e2e/report.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: e2e-report
