name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2 | cut -d "." -f 1,2)" >> $GITHUB_ENV
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests
      run: make integration-test
    - name: Upload code coverage report to Code Climate
      uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: 0215663c97fb7fa30fe9dc409ea016f7219323d0cd9a882a6afe7ead0035d366
      with:
        coverageLocations: cover.out:gocov
        prefix: github.com/${{ github.repository }}
