apiVersion: sync.appuio.ch/v1alpha1
kind: SyncConfig
metadata:
  name: espejo-e2e-test
spec:
  namespaceSelector:
    matchNames:
    - espejo-.*
    labelSelector:
      matchLabels:
        e2e: test
  syncItems:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: espejo-e2e-test-data
    data:
      KEY: ${PROJECT_NAME}
